server:
  port: 8084

spring:
  application:
    name: incident-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/devops_incidents

services:
  config-url: http://localhost:8082/api/v1/config
